# LU Decomposition demo

## Imports

In [17]:
import numpy as np

## Define inputs

#### This is the one of the matrices that was shown in the tutorial.
#### The tol variable is the tolerance for the zero pivot check. In case the pivot in it's absolute value is smaller than the tolerance, the algorithm will stop.

In [18]:
mat = np.array([[1, 3, 1],
                  [2, 8, 1],
                  [1, 10, 4]])
tol = 1e-5

## Extracting dimensions from the matrix, and defining the L and U matrices.

In [19]:
shape = mat.shape
m = shape[0]
n = shape[1]

L = np.eye(m)
U = np.zeros((m, n))

print(f"Dimensions of the matrix: {m}x{n}")

Dimensions of the matrix: 3x3


## LU Algorithm

In [20]:
for i in range(min(n,m)):
    U[i, i:n] = mat[i, i:n]
    if abs(U[i, i]) < tol:
        print("The matrix has a zero pivot")
        break
    else:
        L[i+1:m, i] = mat[i+1:m, i]/U[i, i]
        mat[i+1:m, i+1:n] = mat[i+1:m, i+1:n] - np.outer(L[i+1:m, i], U[i, i+1:n])

## Results

In [21]:
print(f"L = \n{L}")
print(f"U = \n{U}")

L = 
[[1.  0.  0. ]
 [2.  1.  0. ]
 [1.  3.5 1. ]]
U = 
[[ 1.  3.  1.]
 [ 0.  2. -1.]
 [ 0.  0.  6.]]


## Check

In [22]:
print(f"L*U = \n{L@U}")

L*U = 
[[ 1.   3.   1. ]
 [ 2.   8.   1. ]
 [ 1.  10.   3.5]]
